/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentListManager: typeof import('./src/components/ContentListManager.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ExternalPlatformFrame: typeof import('./src/components/ExternalPlatformFrame.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingletonContentManager: typeof import('./src/components/SingletonContentManager.vue')['default']
  }
}
